config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/payments/:token/new', to: 'payments#new', as: 'payments_new'
  get "/create_event/:id", to: "calendars#create_event", as: "create_event"
  get "/oauth2callback", to: "calendars#handle_oauth_callback"
  get '/group/:token', to: 'formats#show', as: 'group_show'
  post '/formats/register', to: 'formats#member_register', as: 'member_register'
  root 'formats#index'
  resources :payments, only: [:create, :edit, :update, :destroy]
  delete 'destroy_selected', to: 'payments#destroy_selected', as: :delete_payments
  resources :formats do
    member do
      get 'edit_group'
      put 'update_group'
      get 'add_member'
      post 'create_member'
    end
  end
end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
  # クラスインスタンス変数を定義
  @member_name = []
  @member_name_keys = []
  @members = []

  # クラスインスタンス変数のアクセサメソッドを定義
  class << self
    attr_accessor :member_name, :member_name_keys, :members
  end

  def index
    @formats = Group.includes(:members)
    @format = GroupMember.new
    self.class.members.clear
    # 新規作成するグループのIDを採番
    if Group.count == 0
      @group_id = 1
    else
      @group_id = Group.maximum(:group_id) + 1
    end
  end

  def show
    @group = Group.find_by(token: params[:token])
    @members = Member.where(group_id: @group.group_id)
    @payments = Payment.where(group_id: @group.group_id)

    @search = @payments.ransack(params[:q])
    @payments = @search.result.includes(:creditor_member).select(:payment_id, :creditor_member_id, :debtor_member_id, :amount)
  end

  # --- グループとメンバーを作成する ---
  def create
    set_member_name
    GroupMember.create_member_accessors(self.class.member_name_keys)
    @format = GroupMember.new(format_params)
    if @format.save(self.class.member_name)
      @group = Group.find(Group.order(group_id: :desc).first.group_id)
      redirect_to group_show_path(token: @group.token)
    else
      render "index"
    end
  end
  # --------------------------------

  # --- グループ名を更新する ---
  def edit_group
    @group = Group.find(params[:id])
  end

  def update_group
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash.now.notice = "グループ情報を更新しました"
    else
      render 'edit_group', status: :unprocessable_entity
    end
  end
  # -------------------------

  # --- メンバー情報を追加・更新・削除する ---
  def edit
    @member = Member.find(params[:id])
    @group = Group.find_by(group_id: @member.group_id)
  end

  def update
    @member = Member.find(params[:id])
    @group = Group.find_by(group_id: @member.group_id)
    if @member.update(member_params)
      flash.now.notice = "メンバー情報を更新しました。"
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @group = Group.find_by(group_id: @member.group_id)

    @members = Member.where(group_id: @group.group_id)
    @payments = Payment.where(group_id: @group.group_id)
    @search = @payments.ransack(params[:q])
    @payments = @search.result.includes(:creditor_member).select(:payment_id, :creditor_member_id, :debtor_member_id, :amount)
    if @member.destroy
      flash.now.notice = "メンバー情報を削除しました。"
    else
      flash.now.alert = "このメンバーには関連する支払い明細があるため、削除できません。"
    end
  end

  def add_member
    @member = Member.new
    @group = Group.find(params[:id])
  end

  def create_member
    @member = Member.new(member_params)
    @group = Group.find_by(group_id: @member.group_id)
    if @member.save
      flash.now.notice = "メンバー情報を登録しました。"
    else
      render 'add_member', status: :unprocessable_entity
    end
  end
  # --------------------------------

  # クラスインスタンス変数（配列）にmember_name(連番)のパラメータの値を格納
  def set_member_name
    self.class.member_name.clear
    self.class.member_name_keys = params[:group_member].keys.select { |key| key.to_s.start_with?("member_name") }
    self.class.member_name_keys.each do |name|
      self.class.member_name << params[:group_member][name]
    end
  end

  private

  def format_params
    member_names = params[:group_member].keys.select { |key| key.to_s.start_with?("member_name") } # member_name(連番)のキーを変数に格納
    permitted_params = [:group_name] + member_names
    params.require(:group_member).permit(permitted_params)
  end

  def group_params
    params.require(:group).permit(:group_id, :group_name, :token)
  end

  def member_params
    params.require(:member).permit(:member_id, :member_name, :group_id)
  end
end

app/helpers/formats_helper.rb
module FormatsHelper
  def update_payments_info(member)
    Payment.where(group_id: member.group_id)
  end

  def get_members_info(member)
    Member.where(group_id: member.group_id)
  end

  def get_search_info(member)
    payments = Payment.where(group_id: member.group_id)
    payments.ransack(params[:q])
  end
end

app/views/formats/_add_member_form.html.erb
<%= turbo_frame_tag @member do %>
    <%= bootstrap_form_with(model: @member, url: create_member_format_path, local: true, data: { action: "turbo:submit-end->modal#close" }) do |form| %>
        <div class="member">
            <%= form.text_field :member_name, maxlength: 8, placeholder: "8文字以内", value: @member.member_name %>
            <%= form.hidden_field :member_id, value: @member.member_id %>
            <%= form.hidden_field :group_id, value: @group.group_id %>
        </div>
        <%= form.submit "登録する", class: "btn btn-outline-primary w-100 mb-3" %>
    <% end %>
<% end %>

app/views/formats/_group.html.erb
<%= turbo_frame_tag group do %>
    <%= group.group_name %>
    <span>
        <%= link_to edit_group_format_path(id: @group.group_id), data: { turbo_frame: "modal" } do %>
            <i class="bi bi-pen edit-group"></i>
        <% end %>
    </span>
<% end %>

app/views/formats/_group_form.html.erb
<%= turbo_frame_tag @group do %>
    <%= bootstrap_form_with(model: @group, url: update_group_format_path, local: true, data: { action: "turbo:submit-end->modal#close" }, method: :put) do |form| %>
        <div class="group">
            <%= form.text_field :group_name, maxlength: 15 %>
            <%= form.hidden_field :group_id, value: @group.group_id %>
            <%= form.hidden_field :token, value: @group.token %>
        </div>
        <div class="actions">
            <%= form.submit "変更する", class: "btn btn-outline-primary w-100" %>
        </div>
    <% end %>
<% end %>

app/views/formats/_member.html.erb
<%= turbo_frame_tag member do %>
    <div class="member">
        <div class="box me-2 mt-2">
            <%= link_to member.member_name, edit_format_path(id: member.member_id), data: { turbo_frame: "modal" }, class:"member-link" %>
        </div>
    </div>
<% end %>

app/views/formats/_member_form.html.erb
<%= turbo_frame_tag @member do %>
    <%= bootstrap_form_with(model: @member, url: format_path, local: true, data: { action: "turbo:submit-end->modal#close" }, method: :put) do |form| %>
        <div class="member">
            <%= form.text_field :member_name, maxlength: 8, value: @member.member_name %>
            <%= form.hidden_field :member_id, value: @member.member_id %>
            <%= form.hidden_field :group_id, value: @group.group_id %>
        </div>
        <%= form.submit "変更する", class: "btn btn-outline-primary w-100 mb-3" %>
    <% end %>

    <%= bootstrap_form_with(model: @member, url: format_path, local: true, data: { turbo_confirm: "このメンバーを削除しますか？", action: "turbo:submit-end->modal#close" }, method: :delete) do |form| %>
        <%= form.submit "削除する", class: "btn btn-outline-danger w-100" %>
    <% end %>
<% end %>

app/views/formats/_member_select.html.erb
<%= turbo_frame_tag "member_select" do %>
    <%= search_form_for(@search, url: group_show_path(token: @group.token), html: { data: {
            turbo_frame: "payment",
            controller: "form",
            action: "input->form#submit"
        }}) do |f| %>
        <%= f.select :creditor_member_member_name_eq,options_for_select([["選択したメンバーの明細だけを表示できます。", ""]] + members.map { |member| [member.member_name, member.member_name] }, @search.creditor_member_member_name_eq),{}, { class: "form-select" } %>
    <% end %>
<% end %>

app/views/formats/_payments.html.erb
<%= turbo_frame_tag "payment" do %>
    <% payments.each do |payment| %>
        <%= render partial: "payments/payment", locals: { payment: payment } %>
    <% end %>
<% end %>

app/views/formats/add_member.html.erb
<%= render "modal", title: "追加" do %>
    <%= render "add_member_form", member: @member %>
<% end %>

app/views/formats/create_member.turbo_stream.erb
<%= turbo_stream.append "members" do %>
    <%= render partial: "formats/member",locals: { member: @member } %>
<% end %>
<%= turbo_stream.update Member.new, "" %>
<%= turbo_stream.replace "member_select" do %>
    <% members = get_members_info(@member) %>
    <% @search = get_search_info(@member) %>
    <%= render partial: "formats/member_select",locals: { members: members } %>
<% end %>
<%= turbo_stream_flash %>

app/views/formats/destroy.turbo_stream.erb
<% if @member.errors.size == 0 %>
    <%= turbo_stream.remove @member %>
<% end %>
<%= turbo_stream.replace "member_select" do %>
    <%= render partial: "formats/member_select",locals: { members: @members } %>
<% end %>
<%= turbo_stream_flash %>

app/views/formats/edit_group.html.erb
<%= render "modal", title: "編集" do %>
    <%= render "group_form", group: @group %>
<% end %>

app/views/formats/show.html.erb
<div class="wrap cover-all mx-auto">
    <header class="p-3 text-center">
        <%= turbo_frame_tag @group do %>
            <%= render partial: "formats/group", locals: { group: @group } %>
        <% end %>
    </header>
    <div class="content px-3">
        <div class="d-flex justify-content-end mt-2">
            <button id="copy_url_button" class="btn btn-sm btn-outline-dark">URLをコピー</button>
        </div>
        <p class="m-0">メンバー
            <span>
                <%= link_to add_member_format_path(id: @group.group_id), data: { turbo_frame: "modal"} do %>
                    <i class="bi bi-plus-circle add-member"></i>
                <% end %>
            </span>
        </p>
        <div id="members" class="d-flex flex-wrap justify-content-start">
            <% @members.each do |member| %>
                <%= render partial: "formats/member", locals: { member: member } %>
            <% end %>
        </div>
        <p class="mt-5 mb-3">支払い明細
            <span>
                <%= link_to payments_new_path(token: @group.token), data: { turbo_frame: "modal"} do %>
                    <i class="bi bi-plus-circle new-payment"></i>
                <% end %>
            </span>
        </p>
        <div id="payments_section">
            <%= turbo_frame_tag "member_select" do %>
                <%= search_form_for(@search, url: group_show_path(token: @group.token), html: { data: {
                        turbo_frame: "payment",
                        controller: "form",
                        action: "input->form#submit"
                    }}) do |f| %>
                    <%= f.select :creditor_member_member_name_eq,options_for_select([["選択したメンバーの明細だけを表示できます。", ""]] + @members.map { |member| [member.member_name, member.member_name] }, @search.creditor_member_member_name_eq),{}, { class: "form-select" } %>
                <% end %>
            <% end %>
            <%= form_with url: delete_payments_path, method: :delete, data: { turbo_confirm: "選択した支払いを完了しますか？" } do %>
                <div id="payments" class="mt-3">
                    <%= turbo_frame_tag "payment" do %>
                        <% @payments.each do |payment| %>
                            <%= render partial: "payments/payment", locals: { payment: payment } %>
                        <% end %>
                    <% end %>
                </div>
                <div class="mt-3">
                    <%= submit_tag "まとめて完了", class: "btn btn-sm btn-outline-success" %>
                </div>
            <% end %>
        </div>
    </div>
    <footer class="fw-light fs-6 p-3">
            <p class="m-0">©︎2024 Tatekae Record</p>
    </footer>
</div>
<script>
    // URLコピー
    var copyButton = document.getElementById('copy_url_button')

    copyButton.addEventListener('click', function(){
        var currentUrl = window.location.href;

        navigator.clipboard.writeText(currentUrl).then(function(){
            alert('URLがクリップボードにコピーされました');
        }).catch(function(err){
            console.error('URLのコピーに失敗しました:',err);
        });
    });
</script>

app/views/formats/update.turbo_stream.erb
<%= turbo_stream.replace @member do %>
    <%= render partial: "formats/member",locals: { member: @member } %>
<% end %>
<%= turbo_stream.replace "payment" do %>
    <% payments = update_payments_info(@member) %>
    <%= render partial: "formats/payments",locals: { payments: payments } %>
<% end %>
<%= turbo_stream.replace "member_select" do %>
    <% members = get_members_info(@member) %>
    <% @search = get_search_info(@member) %>
    <%= render partial: "formats/member_select",locals: { members: members } %>
<% end %>
<%= turbo_stream_flash %>

app/views/formats/update_group.turbo_stream.erb
<%= turbo_stream.replace @group do %>
    <%= render partial: "formats/group",locals: { group: @group } %>
<% end %>
<%= turbo_stream_flash %>