config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/payments/:token/new', to: 'payments#new', as: 'payments_new'
  get "/create_event/:id", to: "calendars#create_event", as: "create_event"
  get "/oauth2callback", to: "calendars#handle_oauth_callback"
  get '/group/:token', to: 'formats#show', as: 'group_show'
  post '/formats/register', to: 'formats#member_register', as: 'member_register'
  root 'formats#index'
  resources :payments, only: [:create, :edit, :update, :destroy]
  delete 'destroy_selected', to: 'payments#destroy_selected', as: :delete_payments
  resources :formats do
    member do
      get 'edit_group'
      put 'update_group'
      get 'add_member'
      post 'create_member'
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  # belongs_to :member, foreign_key: 'creditor_member_id', optional: true
  belongs_to :creditor_member, class_name: 'Member'
  belongs_to :debtor_member, class_name: 'Member'
  belongs_to :group, optional: true

  validates :creditor_member_id, presence: true
  validates :debtor_member_id, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { in: 0..999999 }
  validates :group_id, presence: true
  validates :payment_date, presence: true
  validates :description, length: { in: 0..30 }

  # rubocop:disable Airbnb/OptArgParameters
  def self.ransackable_attributes(auth_object = nil)
    ["creditor_member_id", "debtor_member_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["creditor_member", "debtor_member"]
  end
  # rubocop:enable Airbnb/OptArgParameters
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
    @group = Group.find_by(token: params[:token])
    @members = Member.where(group_id: @group.group_id)
    @creditor_member = Member.new
    @debtor_member = Member.new
  end

  def create
    @payment = Payment.new(payment_params)
    @group = Group.find(@payment.group_id)
    @members = Member.where(group_id: @group.group_id)
    @payments = Payment.where(group_id: @group.group_id)
    if @payment.save
      flash.now.notice = "支払い明細を作成しました"
      @search = @payments.ransack(params[:q])
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @payment = Payment.find(params[:id])
    @group = Group.find(@payment.group_id)
    @members = Member.where(group_id: @group.group_id)
    @creditor_member = Member.find_by(member_id: @payment.creditor_member_id)
    @debtor_member = Member.find_by(member_id: @payment.debtor_member_id)
  end

  def update
    @payment = Payment.find(params[:id])
    @group = Group.find_by(group_id: @payment.group_id)
    @members = Member.where(group_id: @group.group_id)
    @creditor_member = Member.find_by(member_id: @payment.creditor_member_id)
    @debtor_member = Member.find_by(member_id: @payment.debtor_member_id)
    if @payment.update(payment_params)
      flash.now.notice = "支払い明細を更新しました"
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    if @payment.destroy
      flash.now.notice = "支払いが完了しました"
    end
  end

  def destroy_selected
    @target_payments = Payment.where(payment_id: params[:payment_ids])
    @present_flag = @target_payments.present?
    if params[:payment_ids]
      @payments = Payment.where(group_id: @target_payments[0].group_id).where.not(payment_id: @target_payments.pluck(:payment_id))
      @group = Group.find_by(group_id: @target_payments[0].group_id)
      @members = Member.where(group_id: @group.group_id)
      @search = @payments.ransack(params[:q])
      if @target_payments.destroy_all
        flash.now.notice = "選択された支払いを完了しました。"
      end
    else
      flash.now.alert = "完了する支払いを選択してください。"
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:creditor_member_id, :debtor_member_id, :group_id, :amount, :payment_date, :description)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_payment.html.erb
<%= turbo_frame_tag payment do %>
    <div class="row mt-2">
        <div class="form-check col-1 pe-0">
            <%= check_box_tag "payment_ids[]", payment.id, false, class: "form-check-input", id: "flexCheckDefault#{payment.id}" %>
        </div>
        <div id="creditor_member" class="col-3 ps-0">
            <%= payment.creditor_member.member_name %>
        </div>
        <div class="col-1 p-0">
            <i class="bi bi-arrow-right"></i>
        </div>
        <div id="debtor_member" class="col-3 ps-0">
            <%= payment.debtor_member.member_name %>
        </div>
        <div class="col-2 ps-0">
            ¥<%= number_with_delimiter(payment.amount) %>
        </div>
        <div class="col-1">
            <div class="dropdown">
                <i class="bi bi-three-dots-vertical" data-bs-toggle="dropdown" aria-expanded="false"></i>
                <ul class="dropdown-menu">
                    <li>
                        <%= link_to edit_payment_path(id: payment.payment_id), class: "dropdown-item edit", data: { turbo_frame: "modal" } do %>
                            編集
                        <% end %>
                    </li>
                    <li>
                        <%= link_to create_event_path(id: payment.payment_id), class: "dropdown-item create-event", data: { turbo_frame: "modal" } do %>
                            Googleカレンダーに登録
                        <% end %>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-1">
            <%= link_to payment_path(id: payment.payment_id), data: { turbo_method: :delete, turbo_confirm: "支払いを完了します。"} do %>
                <i class="bi bi-check-circle"></i>
            <% end %>
        </div>
    </div>
<% end %>

app/views/payments/_payment_form.html.erb
<%= turbo_frame_tag @payment do %>
    <%= bootstrap_form_with(model: @payment, local: true, data: { action: "turbo:submit-end->modal#close" }) do |form| %>
        <div class="mb-3">
            <div class="dropdown">
                <%= form.select :creditor_member_id, options_for_select([["", nil]] + @members.map { |member| [member.member_name, member.member_id] }, @creditor_member.member_id)  %>
            </div>
        </div>
        <div class="mb-3">
            <div class="dropdown">
                <%= form.select :debtor_member_id, options_for_select([["", nil]] + @members.map { |member| [member.member_name, member.member_id] }, @debtor_member.member_id)  %>
            </div>
        </div>
        <div class="mb-3">
            <div class="amount">
                <%= form.number_field :amount, max: 999999, min: 0 %>
            </div>
        </div>
        <div class="mb-3">
            <div class="description">
                <%= form.text_field :description, maxlength: 30 %>
            </div>
        </div>
        <div class="mb-3">
            <div class="payment_day">
                <%= form.hidden_field :payment_date, value: Date.today %>
            </div>
        </div>
        <%= form.hidden_field :group_id, value: @group.group_id %>
        <div class="actions" >
            <%= form.submit "登録する", class: "btn btn-outline-primary w-100" %>
        </div>
    <% end %>
<% end %>

app/views/payments/_payments.html.erb
<div id="payments_section">
    <%= turbo_frame_tag "member_select" do %>
        <%= search_form_for(@search, url: group_show_path(token: @group.token), html: { data: {
                turbo_frame: "payment",
                controller: "form",
                action: "input->form#submit"
            }}) do |f| %>
            <%= f.select :creditor_member_member_name_eq,options_for_select([["選択したメンバーの明細だけを表示できます。", ""]] + @members.map { |member| [member.member_name, member.member_name] }, @search.creditor_member_member_name_eq),{}, { class: "form-select" } %>
        <% end %>
    <% end %>
    <div id="payments" class="mt-3">
        <%= turbo_frame_tag "payment" do %>
            <% @payments.each do |payment| %>
                <%= render partial: "payments/payment", locals: { payment: payment } %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/payments/_payments_section.html.erb
<div id="payments_section">
    <%= turbo_frame_tag "member_select" do %>
        <%= search_form_for(@search, url: group_show_path(token: @group.token), html: { data: {
                turbo_frame: "payment",
                controller: "form",
                action: "input->form#submit"
            }}) do |f| %>
            <%= f.select :creditor_member_member_name_eq,options_for_select([["選択したメンバーの明細だけを表示できます。", ""]] + @members.map { |member| [member.member_name, member.member_name] }, @search.creditor_member_member_name_eq),{}, { class: "form-select" } %>
        <% end %>
    <% end %>
    <%= form_with url: delete_payments_path, method: :delete, data: { turbo_confirm: "選択した支払いを完了しますか？" } do %>
        <div id="payments" class="mt-3">
            <%= turbo_frame_tag "payment" do %>
                <% @payments.each do |payment| %>
                    <%= render partial: "payments/payment", locals: { payment: payment } %>
                <% end %>
            <% end %>
        </div>
        <div class="mt-3">
            <%= submit_tag "まとめて完了", class: "btn btn-outline-success" %>
        </div>
    <% end %>
</div>

app/views/payments/create.turbo_stream.erb
<%= turbo_stream.append "payment" do %>
    <%= render partial: "payments/payment",locals: { payment: @payment } %>
<% end %>
<%= turbo_stream.replace "payments_section" do %>
    <%= render partial: "payments/payments_section" %>
<% end %>
<%= turbo_stream_flash %>

app/views/payments/destroy.turbo_stream.erb
<%= turbo_stream.remove @payment %>
<%= turbo_stream_flash %>

app/views/payments/destroy_selected.turbo_stream.erb
<% if @present_flag %>
    <%= turbo_stream.remove @target_payments %>
    <%= turbo_stream.replace "payments_section" do %>
        <%= render partial: "payments/payments_section" %>
    <% end %>
<% end %>
<%= turbo_stream_flash %>

app/views/payments/edit.html.erb
<%= render "modal", title: "編集" do %>
    <%= render "payment_form", payment: @payment %>
<% end %>

app/views/payments/new.html.erb
<%= render "modal", title: "追加" do %>
    <%= render "payment_form", payment: @payment %>
<% end %>

app/views/payments/update.turbo_stream.erb
<%= turbo_stream.replace @payment do %>
    <%= render partial: "payments/payment",locals: { payment: @payment } %>
<% end %>
<%= turbo_stream_flash %>